import type { Metadata } from "next";
import {
  Inter,
  Lato,
  Montserrat,
  Open_Sans,
  Poppins,
  Rubik,
  Ubuntu,
} from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import { CircleCheck } from "lucide-react";

const inter = Inter({ subsets: ["latin"], display: "swap" });
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const openSans = Open_Sans({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

const lato = Lato({
  weight: ["400", "900", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const rubik = Rubik({ subsets: ["latin"] });

const ubuntu = Ubuntu({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Consultly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} antialiased relative overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        {children}
        <Toaster
          position="top-right"
          visibleToasts={1}
          icons={{
            success: (
              <CircleCheck size={22} className="fill-green-500 text-gray-75" />
            ),
          }}
          toastOptions={{
            className: "bg-gray-75 text-gray-800",
          }}
        />
      </body>
    </html>
  );
}
