import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import { CircleCheck } from "lucide-react";
import { Toaster as ActionToaster } from "@/components/ui/toaster";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "auto",
});

export const metadata: Metadata = {
  title: "Consultly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} antialiased relative overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        {children}
        <Toaster
          position="top-right"
          visibleToasts={1}
          icons={{
            success: (
              <CircleCheck size={22} className="fill-green-500 text-gray-75" />
            ),
          }}
          toastOptions={{
            className: "bg-gray-75 text-gray-800",
          }}
        />
        <ActionToaster />
      </body>
    </html>
  );
}
