export const countryOptions = [
  "Australia",
  "Austria",
  "Belgium",
  "Bulgaria",
  "Canada",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hong Kong",
  "India",
  "Ireland",
  "Italy",
  "Japan",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Mexico",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Switzerland",
  "United Kingdom",
  "United States",
];

export const meetings = [
  {
    meetingId: "1",
    duration: "15mins",
    status: "paid",
    guest: "Adeleke Muyideen",
    email: "muyideeenadele@gmail.com",
    time: "10:30am → 10:45am",
    date: "Today",
    price: "free",
    meetingType: "Consultation",
  },
  {
    meetingId: "2",
    duration: "30mins",
    status: "in-progress",
    guest: "John Doe",
    email: "johndoe@example.com",
    time: "11:00am → 11:30am",
    date: "May 30 2024",
    price: "$50",
    meetingType: "Follow-up",
  },
  {
    meetingId: "3",
    duration: "1hr",
    status: "confirmed",
    guest: "Jane Smith",
    email: "janesmith@example.com",
    time: "2:00pm → 3:00pm",
    date: "April 6 2024",
    price: "$100",
    meetingType: "Initial Meeting",
  },
  {
    meetingId: "4",
    duration: "45mins",
    status: "pending",
    guest: "Mike Johnson",
    email: "mikejohnson@example.com",
    time: "1:00pm → 1:45pm",
    date: "April 9 2024",
    price: "$75",
    meetingType: "Project Discussion",
  },
  {
    meetingId: "5",
    duration: "20mins",
    status: "confirmed",
    guest: "Emily Davis",
    email: "emilydavis@example.com",
    time: "3:00pm → 3:20pm",
    date: "March 3 2024",
    price: "$30",
    meetingType: "Check-in",
  },
];
